name: Setup ucacher
description: Installs the ucacher binary
branding:
  icon: "sunrise"
  color: "green"
author: Earthly technologies
inputs:
  file_storage_uri:
    description: "URI of the file storage endpoint, for example: s3://<region>/<bucket-name>"
  db_uri:
    description: "Database URI. Only Postgres supported for now: postgres[ql]://[username[:password]@][host[:port],]/database[?parameter_list]"
runs:
  using: "composite"
  steps:
    - name: Downloading ucacher binary
      run: |
        echo "Downloading binary from ${{ inputs.binary-url }}"
        mkdir -p /tmp/ucacher/bin
        curl -L https://github.com/earthly/actions-ucacher/raw/refs/heads/main/bin/ucacher -o /tmp/ucacher/bin/ucacher
        chmod +x /tmp/ucacher/bin/ucacher;
        echo "ucacher downloaded to /tmp/ucacher/bin/ucacher";
      shell: bash

    - name: Creating ucacher wrapper
      run: |
        echo '#!/bin/bash
        UCACHER_DB_URI=${{ inputs.db_uri }} \
        UCACHER_STORAGE=${{ inputs.file_storage_uri }} \
        UCACHER_INSTRUMENTER=strace \
        UCACHER_SHOW_IO=true \
        FORCE_COLOR=1 \
        LOG_LEVEL=debug \
        /tmp/ucacher/bin/ucacher "$@"' > /usr/local/bin/ucacher;
        chmod +x /usr/local/bin/ucacher;
        echo "ucacher installed at /usr/local/bin/ucacher";
      shell: bash

    - name: Set ucacher environment
      run: |
          eval '
            ucacher() {
              AWS_ACCESS_KEY_ID=${{ inputs.aws_access_key }} AWS_SECRET_ACCESS_KEY=${{ inputs.aws_secret_access_key }} UCACHER_DB_URI=${{ inputs.db_uri }} UCACHER_STORAGE=${{ inputs.file_storage_uri }} UCACHER_INSTRUMENTER=strace UCACHER_SHOW_IO=true FORCE_COLOR=1 LOG_LEVEL=debug /tmp/ucacher/bin/ucacher "$@"
            }
          '
      shell: bash
